"use client";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, Text } from "@react-three/drei";
import { Suspense, useMemo, useRef, useState } from "react";
import * as THREE from "three";

type Topic={title:string;category:string;status:"Completed"|"In progress"|"Not started";difficulty:string;hours:number;day:number;owner:"Divya"|"Alex";description:string};
const colorFor=(s:Topic["status"])=>s==="Completed"?"#55d6aa":s==="In progress"?"#ac91ff":"#646b7f";
function Node({topic,position,onSelect}:{topic:Topic;position:[number,number,number];onSelect:(t:Topic)=>void}){const ref=useRef<THREE.Mesh>(null);const [hover,setHover]=useState(false);const color=colorFor(topic.status);useFrame(({clock})=>{if(ref.current){const pulse=topic.status==="In progress"?1+Math.sin(clock.elapsedTime*2.8)*.15:1;ref.current.scale.setScalar((hover?1.32:1)*pulse);}});return <group position={position}><mesh ref={ref} onClick={()=>onSelect(topic)} onPointerOver={e=>{e.stopPropagation();setHover(true);document.body.style.cursor="pointer"}} onPointerOut={()=>{setHover(false);document.body.style.cursor="auto"}}><sphereGeometry args={[topic.status==="Completed"?.105:.09,24,24]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={topic.status==="Not started"?0.25:hover?3.8:2.4} roughness={.3}/></mesh><mesh scale={hover?1.5:1}><sphereGeometry args={[.16,20,20]}/><meshBasicMaterial color={color} transparent opacity={hover?.14:.06}/></mesh>{hover&&<Text position={[0,.28,0]} fontSize={.105} color="white" anchorX="center" outlineWidth={.008} outlineColor="#11131b" maxWidth={2}>{topic.title}</Text>}</group>}
function Path({topics,owner,onSelect}:{topics:Topic[];owner:"Divya"|"Alex";onSelect:(t:Topic)=>void}){const points=useMemo(()=>{const selected=topics.filter(t=>t.owner===owner).sort((a,b)=>a.day-b.day);return selected.map((_,i)=>{const x=(i-(selected.length-1)/2)*.93;const y=Math.sin(i*.9)*.34+(owner==="Divya"?.48:-.48);return [x,y,Math.cos(i*.8)*.3] as [number,number,number]})},[topics,owner]);const line=useMemo(()=>{if(points.length<2)return null;const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));return new THREE.TubeGeometry(curve,Math.max(points.length*12,24),.012,5,false)},[points]);return <group>{line&&<mesh geometry={line}><meshStandardMaterial color={owner==="Divya"?"#8e77ff":"#49bc9a"} emissive={owner==="Divya"?"#6048d5":"#279876"} emissiveIntensity={.65} transparent opacity={.68}/></mesh>}{points.map((p,i)=><Node key={`${owner}-${topics.filter(t=>t.owner===owner).sort((a,b)=>a.day-b.day)[i]?.title}`} topic={topics.filter(t=>t.owner===owner).sort((a,b)=>a.day-b.day)[i]} position={p} onSelect={onSelect}/>)}{points.map((p,i)=><mesh key={`star-${i}`} position={[p[0],p[1]+.25,p[2]]}><sphereGeometry args={[.009,8,8]}/><meshBasicMaterial color="#d0c5ff"/></mesh>)}</group>}
function Dust(){const ref=useRef<THREE.Points>(null);const data=useMemo(()=>{const arr=new Float32Array(210*3);for(let i=0;i<210;i++){arr[i*3]=((i*37)%101)/100*11-5.5;arr[i*3+1]=((i*53)%97)/96*5-2.5;arr[i*3+2]=((i*29)%89)/88*4-2}return arr},[]);useFrame(({clock})=>{if(ref.current)ref.current.rotation.y=clock.elapsedTime*.012});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[data,3]}/></bufferGeometry><pointsMaterial color="#b8b1df" size={.018} transparent opacity={.62} sizeAttenuation/></points>}
export default function Universe({topics,onSelect}:{topics:Topic[];onSelect:(t:Topic)=>void}){return <Canvas camera={{position:[0,0,6],fov:42}} dpr={[1,1.75]} gl={{antialias:true,alpha:true}}><color attach="background" args={["#11131b"]}/><ambientLight intensity={.8}/><pointLight position={[-2,2,3]} intensity={22} color="#7960ed"/><pointLight position={[2,-1,2]} intensity={12} color="#35bd9a"/><Suspense fallback={null}><Dust/><Path topics={topics} owner="Divya" onSelect={onSelect}/><Path topics={topics} owner="Alex" onSelect={onSelect}/></Suspense><OrbitControls enablePan={false} minDistance={4.8} maxDistance={8} minPolarAngle={Math.PI*.32} maxPolarAngle={Math.PI*.68} autoRotate autoRotateSpeed={.22} enableDamping dampingFactor={.08}/></Canvas>}
